//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kcsar.Database.Web
{


  /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kcsar.Database.Web.WebStrings", typeof(WebStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ActionDelete {
            get {
                return ResourceManager.GetString("ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string ActionEdit {
            get {
                return ResourceManager.GetString("ActionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ....
        /// </summary>
        public static string ActionNew {
            get {
                return ResourceManager.GetString("ActionNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ActionSave {
            get {
                return ResourceManager.GetString("ActionSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More.
        /// </summary>
        public static string AddMore {
            get {
                return ResourceManager.GetString("AddMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t understand date.
        /// </summary>
        public static string API_InvalidDate {
            get {
                return ResourceManager.GetString("API_InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string API_NotFound {
            get {
                return ResourceManager.GetString("API_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string API_Required {
            get {
                return ResourceManager.GetString("API_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date required when using custom value..
        /// </summary>
        public static string API_TrainingRecord_CustomExpiryRequired {
            get {
                return ResourceManager.GetString("API_TrainingRecord_CustomExpiryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting documentation (comments or attachments) is required..
        /// </summary>
        public static string API_TrainingRecord_DocumentationRequired {
            get {
                return ResourceManager.GetString("API_TrainingRecord_DocumentationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course has already been awarded for same time..
        /// </summary>
        public static string API_TrainingRecord_Duplicate {
            get {
                return ResourceManager.GetString("API_TrainingRecord_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Change Membership.
        /// </summary>
        public static string ChangeAddMembership {
            get {
                return ResourceManager.GetString("ChangeAddMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Delete.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Animal.
        /// </summary>
        public static string CreateAnimal {
            get {
                return ResourceManager.GetString("CreateAnimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KCSARA Database.
        /// </summary>
        public static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Roster.
        /// </summary>
        public static string FinishRoster {
            get {
                return ResourceManager.GetString("FinishRoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King County Search and Rescue Association.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPrompt {
            get {
                return ResourceManager.GetString("LoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LogoutPrompt {
            get {
                return ResourceManager.GetString("LogoutPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Object_Unit {
            get {
                return ResourceManager.GetString("Object_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate.
        /// </summary>
        public static string Property_BirthDate {
            get {
                return ResourceManager.GetString("Property_BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Property_Email {
            get {
                return ResourceManager.GetString("Property_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Property_Firstname {
            get {
                return ResourceManager.GetString("Property_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Property_Gender {
            get {
                return ResourceManager.GetString("Property_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Property_Lastname {
            get {
                return ResourceManager.GetString("Property_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Property_Password {
            get {
                return ResourceManager.GetString("Property_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Property_Username {
            get {
                return ResourceManager.GetString("Property_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [[ HIDDEN ]].
        /// </summary>
        public static string SensitiveText {
            get {
                return ResourceManager.GetString("SensitiveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in the API. This error has been logged for review..
        /// </summary>
        public static string ServerError_Api {
            get {
                return ResourceManager.GetString("ServerError_Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown API failure..
        /// </summary>
        public static string ServerError_Reason {
            get {
                return ResourceManager.GetString("ServerError_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicants must be {0} years or older.
        /// </summary>
        public static string Validation_ApplicantYoung {
            get {
                return ResourceManager.GetString("Validation_ApplicantYoung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select at least one {0}.
        /// </summary>
        public static string Validation_AtLeastOne {
            get {
                return ResourceManager.GetString("Validation_AtLeastOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized email address.
        /// </summary>
        public static string Validation_BadEmail {
            get {
                return ResourceManager.GetString("Validation_BadEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}.
        /// </summary>
        public static string Validation_Invalid {
            get {
                return ResourceManager.GetString("Validation_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1} characters.
        /// </summary>
        public static string Validation_MaxCharacters {
            get {
                return ResourceManager.GetString("Validation_MaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} or more characters.
        /// </summary>
        public static string Validation_MinCharacters {
            get {
                return ResourceManager.GetString("Validation_MinCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username can only contain numbers, letters, and the characters &apos;.&apos;, &apos;-&apos;, and &apos;_&apos;.
        /// </summary>
        public static string Validation_UsernameFormat {
            get {
                return ResourceManager.GetString("Validation_UsernameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is already in use.
        /// </summary>
        public static string Validation_UsernameTaken {
            get {
                return ResourceManager.GetString("Validation_UsernameTaken", resourceCulture);
            }
        }
    }
}
