// <auto-generated />
namespace Kcsar.Database.Model.Migrations
{
    using System.CodeDom.Compiler;
  using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class ValidationUpdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValidationUpdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201311122014357_ValidationUpdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
